"""deployment-automation 技能实现 - 自动化部署

异常处理:
    - DeploymentError: 部署配置生成相关错误
    - ValueError: 不支持的项目类型或参数
"""

import os
import json
import logging
from pathlib import Path
from typing import Dict, List, Any, Optional
from datetime import datetime

# 导入自定义异常
import sys
sys.path.insert(0, str(Path(__file__).parent.parent))
from exceptions import DeploymentError

# 导入 Pydantic 验证模型
try:
    from pydantic import ValidationError as PydanticValidationError
    from .validation import DeploymentAutomationParams
    PYDANTIC_AVAILABLE = True
except ImportError:
    PYDANTIC_AVAILABLE = False

logger = logging.getLogger(__name__)


# ============== 模板定义 ==============
DOCKERFILE_TEMPLATES = {
    'python': '''# Multi-stage Python Dockerfile
# Generated by lingflow deployment-automation

FROM python:3.11-slim as builder

WORKDIR /app

# Install build dependencies
RUN apt-get update && apt-get install -y \\
    gcc \\
    && rm -rf /var/lib/apt/lists/*

# Copy requirements and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir --user -r requirements.txt

# Final stage
FROM python:3.11-slim

WORKDIR /app

# Copy installed dependencies from builder
COPY --from=builder /root/.local /root/.local

# Copy application code
COPY . .

# Set environment variables
ENV PATH=/root/.local/bin:$PATH
ENV PYTHONUNBUFFERED=1

# Create non-root user
RUN useradd -m -u 1000 appuser && chown -R appuser:appuser /app
USER appuser

# Expose port
EXPOSE {port}

# Health check
HEALTHCHECK --interval=30s --timeout=10s --start-period=5s --retries=3 \\
    CMD curl -f http://localhost:{port}/health || exit 1

# Run the application
CMD ["python", "-m", "{module_name}"]
''',

    'nodejs': '''# Multi-stage Node.js Dockerfile
# Generated by lingflow deployment-automation

FROM node:20-alpine as builder

WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm ci --only=production

# Production stage
FROM node:20-alpine

WORKDIR /app

# Copy dependencies and application code
COPY --from=builder /app/node_modules ./node_modules
COPY . .

# Set environment
ENV NODE_ENV=production

# Add non-root user
RUN addgroup -g 1001 -S nodejs
RUN adduser -S nodejs -u 1001
RUN chown -R nodejs:nodejs /app
USER nodejs

# Expose port
EXPOSE {port}

# Health check
HEALTHCHECK --interval=30s --timeout=10s --start-period=5s --retries=3 \\
    CMD wget --no-verbose --tries=1 --spider http://localhost:{port}/health || exit 1

# Start the application
CMD ["node", "index.js"]
''',

    'go': '''# Multi-stage Go Dockerfile
# Generated by lingflow deployment-automation

FROM golang:1.21-alpine AS builder

WORKDIR /app

# Install dependencies
RUN apk add --no-cache git

# Copy go mod files
COPY go.* ./
RUN go mod download

# Copy source and build
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o main .

# Final stage
FROM alpine:latest

RUN apk --no-cache add ca-certificates curl

WORKDIR /app

# Copy binary from builder
COPY --from=builder /app/main .

# Add non-root user
RUN addgroup -g 1000 appuser && \\
    adduser -D -u 1000 -G appuser appuser && \\
    chown -R appuser:appuser /app
USER appuser

# Expose port
EXPOSE {port}

# Health check
HEALTHCHECK --interval=30s --timeout=10s --start-period=5s --retries=3 \\
    CMD curl -f http://localhost:{port}/health || exit 1

# Run the application
CMD ["./main"]
''',

    'java': '''# Multi-stage Java Dockerfile
# Generated by lingflow deployment-automation

FROM maven:3.9-eclipse-temurin-17 AS builder

WORKDIR /app

# Copy pom.xml and download dependencies
COPY pom.xml .
RUN mvn dependency:go-offline

# Copy source and build
COPY src ./src
RUN mvn clean package -DskipTests

# Runtime stage
FROM eclipse-temurin:17-jre-alpine

WORKDIR /app

# Copy jar from builder
COPY --from=builder /app/target/*.jar app.jar

# Add non-root user
RUN addgroup -g 1000 appuser && \\
    adduser -D -u 1000 -G appuser appuser && \\
    chown -R appuser:appuser /app
USER appuser

# Expose port
EXPOSE {port}

# Health check
HEALTHCHECK --interval=30s --timeout=10s --start-period=30s --retries=3 \\
    CMD wget --no-verbose --tries=1 --spider http://localhost:{port}/actuator/health || exit 1

# Run the application
CMD ["java", "-jar", "app.jar"]
''',

    'static': '''# Static site Dockerfile
# Generated by lingflow deployment-automation

FROM nginx:alpine

# Copy static files
COPY . /usr/share/nginx/html

# Copy custom nginx config if exists
COPY nginx.conf /etc/nginx/conf.d/default.conf 2>/dev/null || true

# Expose port
EXPOSE 80

# Health check
HEALTHCHECK --interval=30s --timeout=10s --start-period=5s --retries=3 \\
    CMD wget --no-verbose --tries=1 --spider http://localhost/ || exit 1
'''
}

# Kubernetes 模板
K8S_DEPLOYMENT_TEMPLATE = '''apiVersion: apps/v1
kind: Deployment
metadata:
  name: {app_name}
  namespace: {namespace}
  labels:
    app: {app_name}
    version: v1
spec:
  replicas: {replicas}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: {app_name}
  template:
    metadata:
      labels:
        app: {app_name}
        version: v1
    spec:
      containers:
      - name: {app_name}
        image: {image_name}:latest
        ports:
        - containerPort: {container_port}
          name: http
        env:
        - name: PORT
          value: "{container_port}"
        - name: ENVIRONMENT
          value: "{environment}"
        {env_vars}
        resources:
          requests:
            cpu: {cpu_request}
            memory: {memory_request}
          limits:
            cpu: {cpu_limit}
            memory: {memory_limit}
        livenessProbe:
          httpGet:
            path: {health_path}
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: {health_path}
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        {volume_mounts}
      {volumes}
      imagePullSecrets:
      - name: registry-credentials
'''

K8S_SERVICE_TEMPLATE = '''apiVersion: v1
kind: Service
metadata:
  name: {app_name}
  namespace: {namespace}
  labels:
    app: {app_name}
spec:
  type: {service_type}
  ports:
  - port: {service_port}
    targetPort: {container_port}
    protocol: TCP
    name: http
  selector:
    app: {app_name}
'''

K8S_INGRESS_TEMPLATE = '''apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {app_name}
  namespace: {namespace}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - {ingress_host}
    secretName: {app_name}-tls
  rules:
  - host: {ingress_host}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {app_name}
            port:
              number: {service_port}
'''

K8S_HPA_TEMPLATE = '''apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {app_name}
  namespace: {namespace}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {app_name}
  minReplicas: {min_replicas}
  maxReplicas: {max_replicas}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
'''

K8S_CONFIGMAP_TEMPLATE = '''apiVersion: v1
kind: ConfigMap
metadata:
  name: {app_name}-config
  namespace: {namespace}
data:
{config_data}
'''

K8S_SECRET_TEMPLATE = '''apiVersion: v1
kind: Secret
metadata:
  name: {app_name}-secret
  namespace: {namespace}
type: Opaque
data:
# Base64 encoded values
# Use: echo -n "value" | base64
{secret_data}
'''

# 蓝绿部署模板
BLUE_GREEN_DEPLOYMENT_TEMPLATE = '''apiVersion: apps/v1
kind: Deployment
metadata:
  name: {app_name}-{color}
  namespace: {namespace}
  labels:
    app: {app_name}
    color: {color}
spec:
  replicas: {replicas}
  selector:
    matchLabels:
      app: {app_name}
      color: {color}
  template:
    metadata:
      labels:
        app: {app_name}
        color: {color}
    spec:
      containers:
      - name: {app_name}
        image: {image_name}:{color}
        ports:
        - containerPort: {container_port}
        env:
        - name: COLOR
          value: "{color}"
        - name: VERSION
          value: "{version}"
        resources:
          requests:
            cpu: {cpu_request}
            memory: {memory_request}
          limits:
            cpu: {cpu_limit}
            memory: {memory_limit}
        livenessProbe:
          httpGet:
            path: {health_path}
            port: {container_port}
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: {health_path}
            port: {container_port}
          initialDelaySeconds: 10
          periodSeconds: 5
'''

BLUE_GREEN_SERVICE_TEMPLATE = '''apiVersion: v1
kind: Service
metadata:
  name: {app_name}
  namespace: {namespace}
  labels:
    app: {app_name}
spec:
  type: ClusterIP
  ports:
  - port: {service_port}
    targetPort: {container_port}
    protocol: TCP
  selector:
    app: {app_name}
    color: {active_color}
'''

BLUE_GREEN_SERVICE_SWITCH_TEMPLATE = '''#!/bin/bash
# Blue-Green Deployment Switch Script
# Generated by lingflow deployment-automation

set -e

APP_NAME="{app_name}"
NAMESPACE="{namespace}"
HEALTH_URL="{health_url}"
NEW_COLOR="{new_color}"

echo "Starting blue-green deployment switch..."
echo "App: $APP_NAME"
echo "New color: $NEW_COLOR"

# Wait for new deployment to be ready
echo "Waiting for $NEW_COLOR deployment to be ready..."
kubectl wait --for=condition=available --timeout=300s \\
    deployment/$APP_NAME-$NEW_COLOR -n $NAMESPACE

# Health check
echo "Performing health check..."
for i in {{1..30}}; do
    if curl -f -s $HEALTH_URL > /dev/null; then
        echo "Health check passed!"
        break
    fi
    if [ $i -eq 30 ]; then
        echo "Health check failed after 30 attempts"
        exit 1
    fi
    echo "Waiting for health check... ($i/30)"
    sleep 2
done

# Switch service to new color
echo "Switching service to $NEW_COLOR..."
kubectl patch svc $APP_NAME -n $NAMESPACE -p '
{{
  "spec": {{
    "selector": {{
      "color": "$NEW_COLOR"
    }}
  }}
}}'

echo "Blue-green deployment switch completed successfully!"
echo "Traffic is now routed to $NEW_COLOR deployment"
'''

# 回滚脚本模板
ROLLBACK_SCRIPT_TEMPLATE = '''#!/bin/bash
# Deployment Rollback Script
# Generated by lingflow deployment-automation

set -e

APP_NAME="{app_name}"
NAMESPACE="{namespace}"
MAX_REVISIONS={max_revisions}

echo "Starting rollback for $APP_NAME..."
echo "Available revisions:"

# List available revisions
kubectl rollout history deployment/$APP_NAME -n $NAMESPACE

if [ -z "$TARGET_REVISION" ]; then
    echo ""
    echo "Usage: TARGET_REVISION=3 ./rollback.sh"
    echo ""
    read -p "Enter revision to rollback to: " TARGET_REVISION
fi

echo "Rolling back to revision $TARGET_REVISION..."

# Perform rollback
kubectl rollout undo deployment/$APP_NAME -n $NAMESPACE --to-revision=$TARGET_REVISION

# Wait for rollout to complete
echo "Waiting for rollout to complete..."
kubectl rollout status deployment/$APP_NAME -n $NAMESPACE --timeout=300s

echo "Rollback completed successfully!"
'''

# CI/CD Pipeline 模板
GITLAB_CI_TEMPLATE = '''# GitLab CI/CD Pipeline
# Generated by lingflow deployment-automation

stages:
  - build
  - test
  - deploy
  - rollback

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"
  IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  IMAGE_LATEST: $CI_REGISTRY_IMAGE:latest

# Build Docker image
build:
  stage: build
  image: docker:24
  services:
    - docker:24-dind
  before_script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
  script:
    - docker build -t $IMAGE_NAME -t $IMAGE_LATEST .
    - docker push $IMAGE_NAME
    - docker push $IMAGE_LATEST
  only:
    - main
    - develop

# Run tests
test:
  stage: test
  image: $IMAGE_LATEST
  services:
    - postgres:15
    - redis:7
  variables:
    POSTGRES_DB: test_db
    POSTGRES_USER: test_user
    POSTGRES_PASSWORD: test_pass
  script:
    - pytest tests/ -v --cov=app
  coverage: '/TOTAL.*\\s+(\\d+%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura

# Deploy to production
deploy:production:
  stage: deploy
  image: bitnami/kubectl:latest
  environment:
    name: production
    url: https://{app_name}.example.com
  script:
    - kubectl set image deployment/{app_name} {app_name}=$IMAGE_NAME -n {namespace}
    - kubectl rollout status deployment/{app_name} -n {namespace} --timeout=300s
  only:
    - main
  when: manual

# Rollback
rollback:production:
  stage: rollback
  image: bitnami/kubectl:latest
  script:
    - kubectl rollout undo deployment/{app_name} -n {namespace}
    - kubectl rollout status deployment/{app_name} -n {namespace} --timeout=300s
  only:
    - main
  when: manual
  allow_failure: true
'''

GITHUB_ACTIONS_TEMPLATE = '''# GitHub Actions CI/CD Pipeline
# Generated by lingflow deployment-automation

name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{{{ env.REGISTRY }}}}
          username: ${{{{ github.actor }}}}
          password: ${{{{ secrets.GITHUB_TOKEN }}}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{{{ env.REGISTRY }}}}/${{{{ env.IMAGE_NAME }}}}:latest
            ${{{{ env.REGISTRY }}}}/${{{{ env.IMAGE_NAME }}}}:${{{{ github.sha }}}}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  test:
    runs-on: ubuntu-latest
    needs: build
    container:
      image: ${{{{ env.REGISTRY }}}}/${{{{ env.IMAGE_NAME }}}}:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run tests
        run: |
          pytest tests/ -v --cov=app

      - name: Upload coverage reports
        uses: codecov/codecov-action@v3

  deploy:
    runs-on: ubuntu-latest
    needs: [build, test]
    if: github.ref == 'refs/heads/main'
    environment:
      name: production
      url: https://{app_name}.example.com
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3

      - name: Configure kubectl
        run: |
          echo "${{{{ secrets.KUBE_CONFIG }}}}" | base64 -d > kubeconfig
          export KUBECONFIG=kubeconfig

      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/{app_name} \\
            {app_name}=${{{{ env.REGISTRY }}}}/${{{{ env.IMAGE_NAME }}}}:${{{{ github.sha }}}} \\
            -n {namespace}
          kubectl rollout status deployment/{app_name} -n {namespace}

  rollback:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    environment:
      name: production
    steps:
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3

      - name: Configure kubectl
        run: |
          echo "${{{{ secrets.KUBE_CONFIG }}}}" | base64 -d > kubeconfig
          export KUBECONFIG=kubeconfig

      - name: Rollback deployment
        run: |
          kubectl rollout undo deployment/{app_name} -n {namespace}
          kubectl rollout status deployment/{app_name} -n {namespace}
'''


# ============== 核心函数 ==============
def execute_skill(params: Dict[str, Any]) -> Dict[str, Any]:
    """执行 deployment-automation 技能

    Args:
        params: 包含以下字段的字典:
            - action: 操作类型 (generate_dockerfile, generate_k8s, blue_green_deploy,
                     rollback, generate_ci, full)
            - project_type: 项目类型 (python, nodejs, go, java, static)
            - app_name: 应用名称
            - port: 应用端口 (默认 8080)
            - output_dir: 输出目录 (默认 ./deployment)
            - 以及其他特定于操作的参数

    Returns:
        操作结果字典

    Raises:
        DeploymentError: 部署配置生成过程中的错误
        ValueError: 不支持的项目类型
    """
    # 使用 Pydantic 验证输入参数
    if PYDANTIC_AVAILABLE:
        try:
            validated = DeploymentAutomationParams(**params)
            # 转换为字典用于后续处理
            params = validated.dict(exclude_unset=True)
        except PydanticValidationError as e:
            return {
                'success': False,
                'error': '输入参数验证失败',
                'validation_errors': e.errors()
            }

    action = params.get('action', 'full')
    app_name = params.get('app_name', 'app')
    port = params.get('port', 8080)
    output_dir = Path(params.get('output_dir', './deployment'))
    project_type = params.get('project_type', 'python')

    result = {
        'action': action,
        'app_name': app_name,
        'files_created': [],
        'messages': [],
        'timestamp': datetime.now().isoformat()
    }

    # 创建输出目录
    output_dir = Path(output_dir)

    try:
        output_dir.mkdir(parents=True, exist_ok=True)
    except (IOError, OSError) as e:
        raise DeploymentError(f"创建输出目录失败: {str(e)}")

    try:
        if action in ['generate_dockerfile', 'full']:
            _generate_dockerfile(params, result, output_dir)

        if action in ['generate_k8s', 'full']:
            _generate_k8s_configs(params, result, output_dir)

        if action in ['blue_green_deploy', 'full']:
            deployment_strategy = params.get('deployment_strategy', 'rolling')
            if deployment_strategy == 'blue_green':
                _generate_blue_green(params, result, output_dir)

        if action in ['rollback', 'full']:
            _generate_rollback_script(params, result, output_dir)

        if action in ['generate_ci', 'full']:
            _generate_ci_cd(params, result, output_dir)

        result['success'] = True
        result['message'] = f"Deployment automation completed successfully for {app_name}"

    except ValueError as e:
        logger.error(f"部署参数错误: {e}")
        result['success'] = False
        result['error'] = str(e)
    except DeploymentError as e:
        logger.error(f"部署配置生成错误: {e}")
        result['success'] = False
        result['error'] = str(e)
    except Exception as e:
        logger.error(f"部署配置生成时出现未预期错误: {e}")
        result['success'] = False
        result['error'] = f'生成失败: {str(e)}'

    return result


def _generate_dockerfile(params: Dict, result: Dict, output_dir: Path):
    """生成 Dockerfile

    Raises:
        DeploymentError: Dockerfile 生成失败
    """
    project_type = params.get('project_type', 'python')
    port = params.get('port', 8080)
    app_name = params.get('app_name', 'app')

    template = DOCKERFILE_TEMPLATES.get(project_type)
    if not template:
        raise ValueError(f"不支持的项目类型: {project_type}")

    content = template.format(
        port=port,
        app_name=app_name,
        module_name=params.get('module_name', 'app')
    )

    dockerfile_path = output_dir / 'Dockerfile'
    try:
        dockerfile_path.write_text(content)
    except (IOError, OSError) as e:
        raise DeploymentError(f"写入 Dockerfile 失败: {str(e)}")
    result['files_created'].append(str(dockerfile_path))
    result['messages'].append(f"Generated Dockerfile for {project_type}")

    dockerfile_path = output_dir / 'Dockerfile'
    dockerfile_path.write_text(content)
    result['files_created'].append(str(dockerfile_path))
    result['messages'].append(f"Generated Dockerfile for {project_type}")

    # 生成 .dockerignore
    dockerignore_content = """# Git
.git
.gitignore

# Documentation
README.md
docs/

# Dependencies (will be installed during build)
node_modules/
__pycache__/
*.pyc
*.pyo
*.pyd
.Python
*.so
*.egg
*.egg-info/

# Test and coverage
tests/
test/
coverage/
*.cover
.hypothesis/
.pytest_cache/

# IDE
.vscode/
.idea/
*.swp
*.swo
*~

# Environment
.env
.env.local
.env.*.local

# Logs
logs/
*.log
npm-debug.log*
yarn-debug.log*

# Misc
.DS_Store
*.bak
*.tmp
"""
    dockerignore_path = output_dir / '.dockerignore'
    dockerignore_path.write_text(dockerignore_content)
    result['files_created'].append(str(dockerignore_path))


def _generate_k8s_configs(params: Dict, result: Dict, output_dir: Path):
    """生成 Kubernetes 配置文件"""
    app_name = params.get('app_name', 'app')
    port = params.get('port', 8080)
    namespace = params.get('k8s_options', {}).get('namespace', 'default')
    container_port = params.get('container_port', port)
    replicas = params.get('replicas', 3)
    image_name = params.get('image_name', f'{app_name}:latest')
    health_path = params.get('health_path', '/health')
    environment = params.get('environment', 'production')

    k8s_dir = output_dir / 'k8s'
    k8s_dir.mkdir(exist_ok=True)

    # 资源配置
    resources = params.get('k8s_options', {}).get('resources', {})
    cpu_request = resources.get('requests', {}).get('cpu', '100m')
    cpu_limit = resources.get('limits', {}).get('cpu', '500m')
    memory_request = resources.get('requests', {}).get('memory', '128Mi')
    memory_limit = resources.get('limits', {}).get('memory', '512Mi')

    # 环境变量
    env_vars = params.get('env_vars', {})
    env_vars_str = ''
    if env_vars:
        for key, value in env_vars.items():
            env_vars_str += f'\n        - name: {key}\n          value: "{value}"'

    # Deployment
    deployment_content = K8S_DEPLOYMENT_TEMPLATE.format(
        app_name=app_name,
        namespace=namespace,
        replicas=replicas,
        image_name=image_name,
        container_port=container_port,
        service_port=port,
        health_path=health_path,
        environment=environment,
        env_vars=env_vars_str,
        cpu_request=cpu_request,
        cpu_limit=cpu_limit,
        memory_request=memory_request,
        memory_limit=memory_limit,
        volume_mounts='',
        volumes=''
    )

    deployment_path = k8s_dir / 'deployment.yaml'
    deployment_path.write_text(deployment_content)
    result['files_created'].append(str(deployment_path))

    # Service
    if params.get('k8s_options', {}).get('create_service', True):
        service_type = params.get('k8s_options', {}).get('service_type', 'ClusterIP')
        service_content = K8S_SERVICE_TEMPLATE.format(
            app_name=app_name,
            namespace=namespace,
            service_port=port,
            container_port=container_port,
            service_type=service_type
        )

        service_path = k8s_dir / 'service.yaml'
        service_path.write_text(service_content)
        result['files_created'].append(str(service_path))

    # Ingress
    if params.get('k8s_options', {}).get('create_ingress', False):
        ingress_host = params.get('k8s_options', {}).get('ingress_host', f'{app_name}.example.com')
        ingress_content = K8S_INGRESS_TEMPLATE.format(
            app_name=app_name,
            namespace=namespace,
            ingress_host=ingress_host,
            service_port=port
        )

        ingress_path = k8s_dir / 'ingress.yaml'
        ingress_path.write_text(ingress_content)
        result['files_created'].append(str(ingress_path))

    # HPA
    if params.get('k8s_options', {}).get('enable_hpa', False):
        min_replicas = params.get('k8s_options', {}).get('min_replicas', 2)
        max_replicas = params.get('k8s_options', {}).get('max_replicas', 10)
        hpa_content = K8S_HPA_TEMPLATE.format(
            app_name=app_name,
            namespace=namespace,
            min_replicas=min_replicas,
            max_replicas=max_replicas
        )

        hpa_path = k8s_dir / 'hpa.yaml'
        hpa_path.write_text(hpa_content)
        result['files_created'].append(str(hpa_path))

    # ConfigMap
    config_data = params.get('config_data', {})
    if config_data:
        config_data_str = '\n'.join([f'  {k}: "{v}"' for k, v in config_data.items()])
        configmap_content = K8S_CONFIGMAP_TEMPLATE.format(
            app_name=app_name,
            namespace=namespace,
            config_data=config_data_str
        )

        configmap_path = k8s_dir / 'configmap.yaml'
        configmap_path.write_text(configmap_content)
        result['files_created'].append(str(configmap_path))

    # Secret template
    secret_content = f"""# {app_name} Secret Configuration
# IMPORTANT: Base64 encode your secrets before adding them
# Use: echo -n "my-secret" | base64

apiVersion: v1
kind: Secret
metadata:
  name: {app_name}-secret
  namespace: {namespace}
type: Opaque
stringData:
  # Add your secrets here (will be base64 encoded by Kubernetes)
  # Example:
  # database-url: "${DATABASE_URL}"
  # api-key: "your-api-key"
"""

    secret_path = k8s_dir / 'secret.yaml'
    secret_path.write_text(secret_content)
    result['files_created'].append(str(secret_path))

    result['messages'].append(f"Generated Kubernetes configurations in {k8s_dir}")


def _generate_blue_green(params: Dict, result: Dict, output_dir: Path):
    """生成蓝绿部署配置"""
    app_name = params.get('app_name', 'app')
    port = params.get('port', 8080)
    namespace = params.get('k8s_options', {}).get('namespace', 'default')
    replicas = params.get('replicas', 3)
    image_name = params.get('image_name', f'{app_name}')
    health_path = params.get('health_path', '/health')
    active_color = params.get('blue_green_options', {}).get('active_color', 'blue')
    health_url = params.get('blue_green_options', {}).get('health_url',
                                                           f'http://{app_name}.{namespace}.svc.cluster.local:{port}{health_path}')

    bg_dir = output_dir / 'k8s' / 'blue-green'
    bg_dir.mkdir(parents=True, exist_ok=True)

    # 资源配置
    resources = params.get('k8s_options', {}).get('resources', {})
    cpu_request = resources.get('requests', {}).get('cpu', '100m')
    cpu_limit = resources.get('limits', {}).get('cpu', '500m')
    memory_request = resources.get('requests', {}).get('memory', '128Mi')
    memory_limit = resources.get('limits', {}).get('memory', '512Mi')

    # Blue deployment
    blue_content = BLUE_GREEN_DEPLOYMENT_TEMPLATE.format(
        app_name=app_name,
        color='blue',
        namespace=namespace,
        replicas=replicas,
        image_name=image_name,
        container_port=port,
        version='v1',
        health_path=health_path,
        cpu_request=cpu_request,
        cpu_limit=cpu_limit,
        memory_request=memory_request,
        memory_limit=memory_limit
    )

    blue_path = bg_dir / 'deployment-blue.yaml'
    blue_path.write_text(blue_content)
    result['files_created'].append(str(blue_path))

    # Green deployment
    green_content = BLUE_GREEN_DEPLOYMENT_TEMPLATE.format(
        app_name=app_name,
        color='green',
        namespace=namespace,
        replicas=replicas,
        image_name=image_name,
        container_port=port,
        version='v1',
        health_path=health_path,
        cpu_request=cpu_request,
        cpu_limit=cpu_limit,
        memory_request=memory_request,
        memory_limit=memory_limit
    )

    green_path = bg_dir / 'deployment-green.yaml'
    green_path.write_text(green_content)
    result['files_created'].append(str(green_path))

    # Service
    service_content = BLUE_GREEN_SERVICE_TEMPLATE.format(
        app_name=app_name,
        namespace=namespace,
        service_port=port,
        container_port=port,
        active_color=active_color
    )

    service_path = bg_dir / 'service.yaml'
    service_path.write_text(service_content)
    result['files_created'].append(str(service_path))

    # Switch script for blue->green
    switch_green = BLUE_GREEN_SERVICE_SWITCH_TEMPLATE.format(
        app_name=app_name,
        namespace=namespace,
        health_url=health_url,
        new_color='green'
    )

    switch_green_path = bg_dir / 'switch-to-green.sh'
    switch_green_path.write_text(switch_green)
    switch_green_path.chmod(0o755)
    result['files_created'].append(str(switch_green_path))

    # Switch script for green->blue
    switch_blue = BLUE_GREEN_SERVICE_SWITCH_TEMPLATE.format(
        app_name=app_name,
        namespace=namespace,
        health_url=health_url,
        new_color='blue'
    )

    switch_blue_path = bg_dir / 'switch-to-blue.sh'
    switch_blue_path.write_text(switch_blue)
    switch_blue_path.chmod(0o755)
    result['files_created'].append(str(switch_blue_path))

    result['messages'].append(f"Generated blue-green deployment configurations in {bg_dir}")


def _generate_rollback_script(params: Dict, result: Dict, output_dir: Path):
    """生成回滚脚本"""
    app_name = params.get('app_name', 'app')
    namespace = params.get('k8s_options', {}).get('namespace', 'default')
    max_revisions = params.get('max_revisions', 10)

    scripts_dir = output_dir / 'scripts'
    scripts_dir.mkdir(exist_ok=True)

    rollback_content = ROLLBACK_SCRIPT_TEMPLATE.format(
        app_name=app_name,
        namespace=namespace,
        max_revisions=max_revisions
    )

    rollback_path = scripts_dir / 'rollback.sh'
    rollback_path.write_text(rollback_content)
    rollback_path.chmod(0o755)
    result['files_created'].append(str(rollback_path))

    # Rollback for blue-green
    bg_rollback_content = '''#!/bin/bash
# Blue-Green Rollback Script
# Generated by lingflow deployment-automation

set -e

APP_NAME="{app_name}"
NAMESPACE="{namespace}"
CURRENT_COLOR="{current_color}"

if [ -z "$CURRENT_COLOR" ]; then
    # Get current color from service selector
    CURRENT_COLOR=$(kubectl get svc $APP_NAME -n $NAMESPACE -o jsonpath='{{.spec.selector.color}}')
fi

# Switch to the other color
if [ "$CURRENT_COLOR" = "blue" ]; then
    NEW_COLOR="green"
else
    NEW_COLOR="blue"
fi

echo "Rolling back from $CURRENT_COLOR to $NEW_COLOR..."

kubectl patch svc $APP_NAME -n $NAMESPACE -p "{\\"spec\\": {\\"selector\\": {\\"color\\": \\"$NEW_COLOR\\"}}}"

echo "Rollback completed! Traffic is now routed to $NEW_COLOR"
'''.format(
        app_name=app_name,
        namespace=namespace,
        current_color=params.get('blue_green_options', {}).get('active_color', 'blue')
    )

    bg_rollback_path = scripts_dir / 'rollback-blue-green.sh'
    bg_rollback_path.write_text(bg_rollback_content)
    bg_rollback_path.chmod(0o755)
    result['files_created'].append(str(bg_rollback_path))

    result['messages'].append(f"Generated rollback scripts in {scripts_dir}")


def _generate_ci_cd(params: Dict, result: Dict, output_dir: Path):
    """生成 CI/CD 配置"""
    app_name = params.get('app_name', 'app')
    namespace = params.get('k8s_options', {}).get('namespace', 'default')
    ci_platform = params.get('ci_platform', 'gitlab')

    ci_dir = output_dir / 'ci-cd'

    if ci_platform == 'github':
        github_actions_content = GITHUB_ACTIONS_TEMPLATE.format(
            app_name=app_name,
            namespace=namespace
        )
        workflows_dir = ci_dir / '.github' / 'workflows'
        workflows_dir.mkdir(parents=True, exist_ok=True)

        workflow_path = workflows_dir / 'ci-cd.yml'
        workflow_path.write_text(github_actions_content)
        result['files_created'].append(str(workflow_path))
        result['messages'].append(f"Generated GitHub Actions workflow")

    else:  # gitlab (default)
        gitlab_ci_content = GITLAB_CI_TEMPLATE.format(
            app_name=app_name,
            namespace=namespace
        )

        gitlab_ci_path = ci_dir / '.gitlab-ci.yml'
        gitlab_ci_path.write_text(gitlab_ci_content)
        result['files_created'].append(str(gitlab_ci_path))
        result['messages'].append(f"Generated GitLab CI configuration")


def detect_project_type(project_path: Path) -> str:
    """自动检测项目类型"""
    # 检查 Python
    if (project_path / 'requirements.txt').exists() or (project_path / 'pyproject.toml').exists():
        return 'python'

    # 检查 Node.js
    if (project_path / 'package.json').exists():
        return 'nodejs'

    # 检查 Go
    if (project_path / 'go.mod').exists():
        return 'go'

    # 检查 Java
    if (project_path / 'pom.xml').exists() or (project_path / 'build.gradle').exists():
        return 'java'

    # 默认为静态站点
    return 'static'
